### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by helenadeus** [shroominic/codeinterpreter-api#1]
Running the demo on readme gives me this error. I'm on python 3.11.3

**Comment by shroominic** [comment]
Hey, thanks for posting it! 
Can you maybe post the entire traceback of the error or a screenshot of it?
And the code you were trying to run this would help a lot 
to get an idea on what went wrong :)

**Comment by shroominic** [comment]
@helenadeus
