### ISSUE TITLE
Code Security

### ISSUE THREAD

**Issue by wizd** [shroominic/codeinterpreter-api#10]
hello, how to prevent hacking if run as public service? e.g. stop running code of:

* download malware
* run shell command
* upload sensitive files to remote server

**Comment by shroominic** [comment]
Thats what CodeBox is for! Its still not 100% ready but try to send out API Keys for testing in a few days. Using the CodeBox API users get assigned their own small cloud hardware so its not running on your server its just connected via API to your backend.
So you dont need to worry about users downloading malware, printing out the ENV Variables or trying to connect to your database.

**Comment by shroominic** [comment]
So for every user that wants to use your service you can start a session and stop it after the user stopps using it. This also works async and in parallel so you dont need to worry about scaling.
