### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by nsankar** [shroominic/codeinterpreter-api#11]
I get the following error from site-packages\codeboxapi\config.py", line 14, in CodeBoxSettings
   CODEBOX_API_KEY: str | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by shroominic** [comment]
Sorry I forgot that this feature is new in python3.10 so you need to use python3.10+ for now. But I try to change this soon so you can also use 3.9+ or maybe even 3.8+

**Comment by nsankar** [comment]
@shroominic  Got it. Would be great If you could enable it for Python 3.9+ . Thanks

**Comment by shroominic** [comment]
Should be working now in v0.0.6 👍🏼

**Comment by shroominic** [comment]
@nsankar
