### ISSUE TITLE
nothing was plotted

### ISSUE THREAD

**Issue by tymss** [shroominic/codeinterpreter-api#156]
I have tried to run this code both in my local environment (MacOS) and in Colab, but nothing was plotted. Why?
![企业微信20240527-120717](https://github.com/shroominic/codeinterpreter-api/assets/25364203/6f0c7e25-0456-4695-b790-547759d1e656)
![企业微信20240527-120733](https://github.com/shroominic/codeinterpreter-api/assets/25364203/caccaf8d-a680-409b-a07d-b7df2b111ee0)

**Comment by shroominic** [comment]
Please read what the LLM responded:
Its not plotting because the plot would be infinite so you need to tell it to only plot a certain rainge...
