### ISSUE TITLE
setting for chat gpt turbo 3.5

### ISSUE THREAD

**Issue by bahman7745** [shroominic/codeinterpreter-api#16]
hi
how set model for chat gpt turbo 3.5
and how set open ai api

**Comment by juananpe** [comment]
> how set model for chat gpt turbo 3.5

you can pass it as a parameter when instantiating the `CodeInterpreterSession` class, as follows:
```
    async with CodeInterpreterSession(model="gpt-3.5-turbo") as session:
```
> and how set open ai api

either set it as an environment variable:
```
$ export OPENAI_API_KEY=TYPE_YOUR_KEY_HERE
$ python yourscript.py
```
or create a .env file in the same directory as your script and set your API keys there
(you can use .env.example as a template https://github.com/shroominic/codeinterpreter-api/blob/main/.env.example)

Beware, there is a PR (https://github.com/shroominic/codeinterpreter-api/pull/14) awaiting to fix an issue related to this way of setting the API key.
