### ISSUE TITLE
No module named 'codeboxapi.schema'

### ISSUE THREAD

**Issue by ElioErrico** [shroominic/codeinterpreter-api#160]
Hello guys trying to run the code in google colab notebook, but having some issues...:

_First block_:
```
import os
os.environ["OPENAI_API_KEY"] = "sk-proj--...."
os.environ["CODEBOX_API_KEY"] = "local"
```

_Second block:_
`!pip install codeinterpreterapi`

_Third block:_
`from codeinterpreterapi import CodeInterpreterSession, settings`

_Error:_
```
  from codeinterpreterapi.config import settings
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-8a741c5e7481> in <cell line: 1>()
----> 1 from codeinterpreterapi import CodeInterpreterSession, settings

1 frames
/usr/local/lib/python3.10/dist-packages/codeinterpreterapi/schema.py in <module>
      2 from typing import Any
      3 
----> 4 from codeboxapi.schema import CodeBoxStatus
      5 from langchain_core.messages import AIMessage, HumanMessage
      6 from langchain_core.pydantic_v1 import BaseModel

ModuleNotFoundError: No module named 'codeboxapi.schema'

```
Seems to me that some problem occurs in codebox library.
Running:
```
!pip install codeboxapi
!pip install aiofiles
from codeboxapi.schema import CodeBoxStatus
```
I get the same error.

Any halp how to fix it?

**Comment by shroominic** [comment]
thanks for notifying me on this and sorry for the inconvenience I just released a new version of codeboxapi (v0.2) but I have not locked the version in codeinterpreterapi and it had some breaking changes

TO FIX: install the newest version of codeinterpreterapi==0.1.18 with package lock to older version of codeboxapi
