### ISSUE TITLE
Run project using Google colab/ any other notebook

### ISSUE THREAD

**Issue by berdugoyohan** [shroominic/codeinterpreter-api#17]
1. The first issue was
`RuntimeError: asyncio.run() cannot be called from a running event loop` this error is caused by using a notebook and has been fixed.

2. I add the OPENAI_API_KEY in variables, after it didn't work add .env file with the key, additionally add on the code:
`OPENAI_API_KEY = 'sk-XXXXX'`
 I got: `ValueError: OpenAI API key missing.`

Any idea?

**Comment by shroominic** [comment]
Hey @berdugoyohan in a notebook it already runs inside an async environment so you dont need to do asyncio.run().
You can just try like in this example:
<img width="520" alt="Screenshot 2023-07-17 at 22 54 22" src="https://github.com/shroominic/codeinterpreter-api/assets/34897716/d7147ad6-0aa7-45a3-bebd-85ec2f297c7f">

**Comment by berdugoyohan** [comment]
It's exactly how I implement it. The issue is with the OPENAI_API_KEY.

<img width="817" alt="image" src="https://github.com/shroominic/codeinterpreter-api/assets/1176219/c888f9b4-43a9-47b3-a094-c64232aebf6d">

**Comment by juananpe** [comment]
Try this:
```python
from codeinterpreterapi import CodeInterpreterSession

session=CodeInterpreterSession(openai_api_key="sk-----------------------",model="gpt-3.5-turbo")
response = await session.generate_response(
        "Plot the bitcoin chart of 2023 YTD"
    )

print("AI: ", response.content)

for file in response.files:
    file.show_image()

```
<img width="1159" alt="image" src="https://github.com/shroominic/codeinterpreter-api/assets/1078305/b3e64440-3a5b-4cad-9f9d-2033a47c5a39">

**Comment by smerrill726** [comment]
wow that fixed my #25 

thank you! 

so why is the model gpt-3.5-turbo and not gpt-4-code-interpreter?

**Comment by shroominic** [comment]
you need to input payment details on your openai account to access gpt-4

**Comment by sinjorjob** [comment]
I ran the following code on JupyterNotebook and got the same error. There seems to be some other problem.

AI: Sorry, something went wrong while generating your response.Please try again or restart the session.

```python
from codeinterpreterapi import CodeInterpreterSession

session=CodeInterpreterSession(openai_api_key="sk-----------------------",model="gpt-3.5-turbo")
response = await session.generate_response(
        "Plot the bitcoin chart of 2023 YTD"
    )

print("AI: ", response.content)

for file in response.files:
    file.show_image()
```

<img width="517" alt="image" src="https://github.com/shroominic/codeinterpreter-api/assets/34405452/a68d901b-bc0d-4cd4-aac2-1fe463da072b">

**Comment by berdugoyohan** [comment]
@sinjorjob - I go over the code and this error string is looked like a generic error that envelop many other error.
You can see it here:
https://github.com/shroominic/codeinterpreter-api/blob/841c3cbd88cd313583f0db14e3b58a0725ae9e33/codeinterpreterapi/session.py#L189

**Comment by smerrill726** [comment]
@shroominic yea it's strange I have payment details and chatgpt plus all setup. have had it for months

<img width="916" alt="Screenshot 2023-07-19 at 9 42 41 AM" src="https://github.com/shroominic/codeinterpreter-api/assets/43649612/056539fb-e672-4cc4-b200-8ef833e08f4c">

What is weird is that I still get code interpreter functionality (passing documents)  using the model "gpt-3.5-turbo"

**Comment by smerrill726** [comment]
@smerrill726 

> @shroominic yea it's strange I have payment details and chatgpt plus all setup. have had it for months
> 
> <img alt="Screenshot 2023-07-19 at 9 42 41 AM" width="916" src="https://user-images.githubusercontent.com/43649612/254592171-056539fb-e672-4cc4-b200-8ef833e08f4c.png">
> What is weird is that I still get code interpreter functionality (passing documents) using the model "gpt-3.5-turbo"

I was confused, chatgpt-plus and API access are two seperate things: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

**Comment by sinjorjob** [comment]
> 

Thank you very much.
I checked the error content in the relevant code and found that the error object was empty.
I think there is a difference between the two environments (perhaps a module dependency issue?), because it was fine on Google coraboratory, but not on my local Win10 environment. I wonder if it is an environmental difference (perhaps a module dependency issue?).

**Comment by shroominic** [comment]
> @smerrill726
> 
> > @shroominic yea it's strange I have payment details and chatgpt plus all setup. have had it for months
> > <img alt="Screenshot 2023-07-19 at 9 42 41 AM" width="916" src="https://user-images.githubusercontent.com/43649612/254592171-056539fb-e672-4cc4-b200-8ef833e08f4c.png">
> > What is weird is that I still get code interpreter functionality (passing documents) using the model "gpt-3.5-turbo"
> 
> I was confused, chatgpt-plus and API access are two separate things: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

No that ChatGPT payment does not have something todo with the platform.openai.com so you need to put your payment details there. It does not matter if you have ChatGPT Plus

**Comment by Hau519** [comment]
I did have my payment details and I even had completed payment before July 6 for api and I still could not use gpt4 api.

**Comment by Hau519** [comment]
I did have my payment set up and I did have previous payment before July 6 for using api. Still I cannot access gpt4 api><

**Comment by berdugoyohan** [comment]
For the past few hours (around 6-7 hours ago), I have been facing an issue with my collab. When attempting to run it, the process starts but then stuck(the async request seems to initiate but never completes or returns any result.). I have tried using various models, including gpt-3.5 and gpt-4, as well as different versions, but all of them are affected by the same problem.

Has anyone else experienced a similar issue?
<img width="1253" alt="image" src="https://github.com/shroominic/codeinterpreter-api/assets/1176219/54a7802c-3276-4915-b390-34051c7456ca">

**Comment by daniel-counto** [comment]
> For the past few hours (around 6-7 hours ago), I have been facing an issue with my collab. When attempting to run it, the process starts but then stuck(the async request seems to initiate but never completes or returns any result.). I have tried using various models, including gpt-3.5 and gpt-4, as well as different versions, but all of them are affected by the same problem.
> 
> Has anyone else experienced a similar issue? <img alt="image" width="1253" src="https://user-images.githubusercontent.com/1176219/257072043-54a7802c-3276-4915-b390-34051c7456ca.png">

I face the same error. The process is running forever, what's the issue?

**Comment by ndfriedman** [comment]
> https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

I have the same issue

**Comment by ndfriedman** [comment]
Same issue with the code not completing or returning anything

**Comment by RookyCoder** [comment]
> syntax error: `await` outside function? Just wondering how does python allow `await` without async function??
