### ISSUE TITLE
Error communicating with OpenAI.

### ISSUE THREAD

**Issue by LeiShenVictoria** [shroominic/codeinterpreter-api#19]
Hi, I have two questions:
(1) An error when running the example code to plot the bitcoin chart of 2023:
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 2.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
(2) How do u achieve the internet access function?
Thx

**Comment by shroominic** [comment]
1. 
Hey I think APIConnectionError has something todo with your internet connection or maybe you disables access for python.

2. 
OpenAI is activly disabling internet access so I just did not do anything so its enabled by default :D
