### ISSUE TITLE
Error communicating with OpenAI.

### ISSUE THREAD

**Issue by abebin** [shroominic/codeinterpreter-api#22]
**After installing all required packages, I'm running the following code:**

```python
from codeinterpreterapi import CodeInterpreterSession, File


async def main():
    # context manager for auto start/stop of the session
    async with CodeInterpreterSession() as session:
        # define the user request
        user_request = "What are the headers?"
        files = [
            File.from_path("...... (Path censored intentionally"),
        ]

        # generate the response
        response = await session.generate_response(
            user_request, files=files
        )

        # output to the user
        print("AI: ", response.content)
        for file in response.files:
            file.show_image()


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
```

**I'm getting the following error:**
```
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
```
Any ideas of why this happens?

Thanks

**Comment by shroominic** [comment]
This problem is with the openai api so maybe something is wrong with your payment details, your internet connection or your account. You can maybe try if the normal chatgpt API works and see if you get the same error.

**Comment by 1073710317** [comment]
got the same error

**Comment by smallchao** [comment]
same error... I have tested my openai key and it is usable.

**Comment by 1073710317** [comment]
> same error... I have tested my openai key and it is usable.

你也是用的代理吗，我后来通过设置代理，可以跑通了

**Comment by shroominic** [comment]
Maybe the problem with OpenAI is that your account does not have access to GPT-4 (which is default) so you can set it to GPT-3.5:
`async with CodeInterpreterSession("gpt-3.5-turbo") as session:`

**Comment by ndfriedman** [comment]
That didn't fix it for me either.  I can query the api the way the open-ai website describes but cant use codeinterpreter-api

**Comment by shawn-stack25** [comment]
I used the [solution](https://github.com/langchain-ai/langchain/issues/5296) from this thread and it seemed to fix my issue. However, I get this "AI:  Agent stopped due to iteration limit or time limit." when trying to run the bitcoin example. I was able to run the plot_sin_wave without any issues though.

**Comment by salvinoto** [comment]
> I used the [solution](https://github.com/langchain-ai/langchain/issues/5296) from this thread and it seemed to fix my issue: `bash /Applications/Python*/Install\ Certificates.command` However, I get this "AI:  Agent stopped due to iteration limit or time limit." when trying to run the bitcoin example. I was able to run the plot_sin_wave without any issues though. 

Solved issue for me as well

**Comment by baomuhedao** [comment]
> 

你的代理设置是如何设置的啊？
