### ISSUE TITLE
Is there a way to save the files?

### ISSUE THREAD

**Issue by mrbende** [shroominic/codeinterpreter-api#31]
I cannot seem to save the images once they're generated. Only `show_image()` seems to be available.  Any way to save the png locally once it has been generated?

Thanks, this is awesome work!!

**Comment by juananpe** [comment]
You can use the `save()` method of File class: 

```
        print("AI: ", response.content)
        for file in response.files:
            file.show_image()
            file.save("bitcoin_chart.png")
```

**Comment by shroominic** [comment]
https://github.com/shroominic/codeinterpreter-api/blob/ed051348b93f86923cf5251ebb2dced6634fbf49/codeinterpreterapi/schema/file.py#L34C1-L39C49

Here you can have a look into how the File Class works. There is also an async version :)
