### ISSUE TITLE
asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by Kashif-Raza6** [shroominic/codeinterpreter-api#35]
I am running the following code but following error keep throwing:
Code:
`
async def main():
    async with CodeInterpreterSession() as session:
        response = await session.generate_response(
            "Plot the relative performance of tech giants (Apple, Google, Microsoft, Amazon) in 2023."
        )

        print("AI: ", response.content)
        for file in response.files:
            file.show_image()

if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
`

error:
![image](https://github.com/shroominic/codeinterpreter-api/assets/96944736/623d775f-b942-44ef-b215-6da7e30f515d)

**Comment by juananpe** [comment]
It seems that you are trying to run the code in Colab (or a Jupyten Notebook)
If so, you should follow these instructions https://github.com/shroominic/codeinterpreter-api/issues/17. And specifically this example https://github.com/shroominic/codeinterpreter-api/issues/17#issuecomment-1638904221.
