### ISSUE TITLE
Importing error 

### ISSUE THREAD

**Issue by SijfWillem** [shroominic/codeinterpreter-api#41]
When importing I get a TypeError saying: 

TypeError: issubclass() arg 1 must be a class

![Screenshot 2023-07-21 at 11 34 24](https://github.com/shroominic/codeinterpreter-api/assets/38949526/a89b85e7-e1d6-49dd-b384-9693bef1a906)

This prevents me from using the tool at all. What to do?

**Comment by Ebinjose10** [comment]
what python version are you using
