### ISSUE TITLE
AI:  Sorry, something went while generating your response.Please try again or restart the session.

### ISSUE THREAD

**Issue by Zixuan-Xu-GodVision** [shroominic/codeinterpreter-api#48]
When I ran the sample script, I encountered some problems. When I run it on Google cloba, it can run normally, but when I run it locally on my computer, I have tried both windows 11 and linux systems. The following error always occurs:

Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 2.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
AI:  Sorry, something went while generating your response.Please try again or restart the session.

I saw your comment on other bug issues, but I still can't solve this bug, can you explain in detail how to solve this problem please.  

![image](https://github.com/shroominic/codeinterpreter-api/assets/100177339/3ac51f3f-5b8a-4856-a9f5-74c56abda229)

**Comment by Zixuan-Xu-GodVision** [comment]
In addition，when I run the code in the command line, it shows the error:ValueError: I/O operation on closed pipe

![image](https://github.com/shroominic/codeinterpreter-api/assets/100177339/18c3731a-a32d-4c48-97eb-765641cffd39)

my code is: 
![image](https://github.com/shroominic/codeinterpreter-api/assets/100177339/d7e7697b-b6f4-4fbb-9f91-e1b181d18a45)

Anyone meet the same issue could help? :)

**Comment by TheZaind** [comment]
yes same problem... also did a issue an houre ago 😅

**Comment by shroominic** [comment]
You can enable detailed_error to get more info on what happened.
https://github.com/shroominic/codeinterpreter-api/issues/25#issuecomment-1641722819

**Comment by Zixuan-Xu-GodVision** [comment]
> You can enable detailed_error to get more info on what happened. [#25 (comment)](https://github.com/shroominic/codeinterpreter-api/issues/25#issuecomment-1641722819)

I enabled the detailed_error, and got the error:AI:  Error in CodeInterpreterSession: APIConnectionError  - Error communicating with OpenAI, and I don't think is my API problem, cause it worked on the google colab.

I think maybe is the langchain configuration file problem， as shown in the pic

![image](https://github.com/shroominic/codeinterpreter-api/assets/100177339/46c8b6f8-4cd8-4413-aa56-a5a188343ad2)

**Comment by Zixuan-Xu-GodVision** [comment]
@shroominic Do you know how to fix this ?

**Comment by JorisBloemen** [comment]
I solved this by using a different python version was on `3.11.1` and got it to run on `3.9.6`. I also had to add the model to the session: `session = CodeInterpreterSession(model="gpt-3.5-turbo")`

**Comment by shroominic** [comment]
When there is an error with OpenAI you need to make sure your API Key is valid and connected to your account

**Comment by Zixuan-Xu-GodVision** [comment]
> I solved this by using a different python version was on `3.11.1` and got it to run on `3.9.6`. I also had to add the model to the session: `session = CodeInterpreterSession(model="gpt-3.5-turbo")`

I tried both python=3.11.1 and 3.9.6, but it didn't work.

**Comment by Zixuan-Xu-GodVision** [comment]
> When there is an error with OpenAI you need to make sure your API Key is valid and connected to your account

I 'm sure my API key is valid, because it worked well on GooogleColab.
