### ISSUE TITLE
Will you guys support azure openai api?

### ISSUE THREAD

**Issue by wangxing7714436** [shroominic/codeinterpreter-api#51]
Hi, didn't see the azure openai api support with current version, will you guys add this option in the future?

**Comment by shroominic** [comment]
I think you can just replace ChatOpenAI with the Azure equivalent here:
https://github.com/shroominic/codeinterpreter-api/blob/66759f263f497c691ada5cefbdf89edc3e642baa/codeinterpreterapi/session.py#L66C9-L72C10

**Comment by wangxing7714436** [comment]
![image](https://github.com/shroominic/codeinterpreter-api/assets/31149248/b5ea1efb-4653-4099-917f-f08ede2f3ed1)
Tried but still raising valueerror: OpenAI API key missing

![image](https://github.com/shroominic/codeinterpreter-api/assets/31149248/2f76b6d1-68eb-43be-811f-d311db7795c1)
