### ISSUE TITLE
Question on the choice of temperature=0.03

### ISSUE THREAD

**Issue by weiqiji** [shroominic/codeinterpreter-api#52]
https://github.com/shroominic/codeinterpreter-api/blob/66759f263f497c691ada5cefbdf89edc3e642baa/codeinterpreterapi/session.py#L67C15-L67C15

Can someone elaborate on the choice of temperature=0.03 instead of 0.0?

**Comment by shroominic** [comment]
When something goes wrong and it tries automatically again it should be a slightly different approach. 
But feel free to prove me wrong if you think 0 is better :)

**Comment by weiqiji** [comment]
I don't have particular opinion on the choice. The idea of adding some randomness for exploration sounds intuitive.
