### ISSUE TITLE
AzureOpenAI chat Support

### ISSUE THREAD

**Issue by sankethgadadinni** [shroominic/codeinterpreter-api#53]
I replaced ChatOpenAI with the following

AzureChatOpenAI(
            model = 'gpt-4',
            temperature=0.03,
            openai_api_base='',
            openai_api_version="2023-07-01-preview",
            deployment_name='',
            openai_api_key='',
            openai_api_type="azure",
            max_retries=3,
            request_timeout=60*3
        )

but it is throwing me this error.

  File "/usr/local/lib/python3.10/dist-packages/langchain/chat_models/openai.py", line 103, in _convert_dict_to_message
    content = _dict["content"] or ""  # OpenAI returns None for tool invocations
KeyError: 'content'

**Comment by bhctest123** [comment]
you need to add the url for the endpoint to make this work

https://[YOUR-SUBDOMAIN].openai.azure.com/

**Comment by rabsef-bicrym** [comment]
Please note that `functions` is only tolerated by the `2023-07-01-preview` model of the Azure implementation.

See [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#functioncall).

I'm going to try to drop a version of this project on my fork that has a .env setting for Azure or OpenAI which should allow the user to switch between easily (assuming they're using a compatible Azure model). I hope this is helpful. Should be just a day more, or so.


`.env.example` for the version I'm working on here:
```
IMPLEMENTATION= "openai" # "openai" for openai api, "azure" for azure deployed openai models [hereafter 'ADOM']
AI_API_KEY= # your openai api key (required)
AI_API_MODEL= "gpt-4" # your openai model (optional, for ADOM, 'engine' name, e.g. "my-deployed-gpt")
AZURE_API_BASE= # your azure base url (optional, required for ADOM)
AZURE_API_VERSION= # your azure version, e.g. "2023-03-15-preview" (optional, required for ADOM)
CODEBOX_API_KEY= # your codebox api key (optional, required for production)
VERBOSE=False # set to True to enable verbose logging
```

**Comment by rabsef-bicrym** [comment]
I have this performing the first function call in `plot_sin_wave.py` and getting a `200` response. The responses between OpenAI and Azure in Postman for the same call appear largely identical but for Azure not including the `content: Null` key/value that OpenAI does when using a `function_call` (see below). Nonetheless, I'm getting the "Something went wrong while generating your response" error after that `200` code.

OpenAI Response per Postman:
```
{
    "id": "<elided>",
    "object": "chat.completion",
    "created": <elided>,
    "model": "gpt-4-0613",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": null,
                "function_call": {
                    "name": "python",
                    "arguments": "import numpy as np\nimport matplotlib.pyplot as plt\n\nx = np.linspace(0, 2 * np.pi, 100)\ny = np.sin(x)\n\nplt.plot(x, y)\nplt.title('Sin Wave')\nplt.xlabel('x')\nplt.ylabel('sin(x)')\nplt.grid(True)\nplt.show()"
                }
            },
            "finish_reason": "function_call"
        }
    ],
    "usage": {
        "prompt_tokens": 358,
        "completion_tokens": 69,
        "total_tokens": 427
    }
}
```

Azure Response per Postman:
```
{
    "id": "<elided>",
    "object": "chat.completion",
    "created": <elided>,
    "model": "gpt-4",
    "prompt_annotations": [
        {
            "prompt_index": 0,
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": false,
                    "severity": "safe"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            }
        }
    ],
    "choices": [
        {
            "index": 0,
            "finish_reason": "function_call",
            "message": {
                "role": "assistant",
                "function_call": {
                    "name": "python",
                    "arguments": "import matplotlib.pyplot as plt\nimport numpy as np\n\n# Create a time array from 0..100 sampled at 0.1 second steps\nt = np.arange(0.0, 10.0, 0.1)\n\n# Create a sin wave from the time array\ns = np.sin(t)\n\n# Create a figure and a set of subplots\nfig, ax = plt.subplots()\n\n# Plot the sin wave\nax.plot(t, s)\n\n# Set labels and title\nax.set(xlabel='time (s)', ylabel='voltage (mV)', title='Simple Sin Wave')\n\n# Set grid\nax.grid()\n\n# Show the plot\nplt.show()"
                }
            },
            "content_filter_results": {}
        }
    ],
    "usage": {
        "completion_tokens": 145,
        "prompt_tokens": 358,
        "total_tokens": 503
    }
}
```

I've tried adding some additional debugging to see where things are going wrong but I'm not finding it - thoughts?

**Comment by ventz** [comment]
Running into the same:

> AI:  Sorry, something went while generating your response.Please try again or restart the session.


Ex, when asking "Plot the Tesla stock price YTD" (which works with OpenAI)

```
 Running code in container... import yfinance as yf

# Download Tesla's stock price data

data = yf.download('TSLA', start='2021-01-01', end='2021-12-31')

# Plot the closing price
data['Close'].plot(title='Tesla Stock Price YTD')
AI:  Sorry, something went while generating your response.Please try again or restart the session.
```

Using the correct env in the code:

```
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-07-01-preview"
os.environ["OPENAI_API_BASE"] = "https://redacted.openai.azure.com"
os.environ["OPENAI_API_KEY"] = "redacted"
os.environ["DEPLOYMENT_NAME"] = "gpt-4"
```

**Comment by sankethgadadinni** [comment]
Thanks, It works if I pass LLM object into CodeInterpreterSession.


llm = AzureChatOpenAI(
                temperature=0.3,
                deployment_name=deployment_name,
                max_retries=3,
                request_timeout=60 * 3,
            )
            
            
async with CodeInterpreterSession(llm=llm) as session:

**Comment by rabsef-bicrym** [comment]
Thanks for making these adjustments - it appears to be working w/ the recent changes!
