### ISSUE TITLE
FileNotFoundError all the times

### ISSUE THREAD

**Issue by Hau519** [shroominic/codeinterpreter-api#55]
I managed to run many things before for my project and suddenly this morning around 9:30-10 until now I kept having this error even for file that already works before. Then I tried the analyze_dataset in the examples file and same thing happened. 
And I added in the require to print out the current working directory, no matter where I am, it come here to look for the file: github\\codeinterpreter-api\\tests\\.codebox. 

![MicrosoftTeams-image (16)](https://github.com/shroominic/codeinterpreter-api/assets/65142251/0dc95635-865e-4c4b-8e65-e77bf0f602d0)

**Comment by shroominic** [comment]
Maybe you changed your current terminal location from where you are executing python? FileNotFound is about 'examples/assets/iris.csv' which is a relative path. You can also try changing the path to an absolute one, so starting with a /.
