### ISSUE TITLE
Running non stop in Colab

### ISSUE THREAD

**Issue by tytung2020** [shroominic/codeinterpreter-api#60]
The code seems to be running non stop for my implementation in Colab:
![Screenshot (448)](https://github.com/shroominic/codeinterpreter-api/assets/37324680/39fdac33-3010-41ad-af96-23510190c000)

Has anyone try this in the colab notebook?

**Comment by berdugoyohan** [comment]
> The code seems to be running non stop for my implementation in Colab: ![Screenshot (448)](https://user-images.githubusercontent.com/37324680/257678094-39fdac33-3010-41ad-af96-23510190c000.png)
> 
> Has anyone try this in the colab notebook?

Try to upgrade to version 0.0.9 it will solve the issue of infinite loop.
