### ISSUE TITLE
Does not plot chart

### ISSUE THREAD

**Issue by daniel-counto** [shroominic/codeinterpreter-api#65]
Ran this in Colab, it does not seem to plot the chart? any libraries need to be imported?

![image](https://github.com/shroominic/codeinterpreter-api/assets/140989990/366a0462-f47c-44f2-abf9-a4c1a2b2f9e8)

Also its knowledge seems to stuck in 2022.
![image](https://github.com/shroominic/codeinterpreter-api/assets/140989990/b4d3e55f-37f9-445f-af1e-17be03565c82)

FYI, I don't use the codebox api and have pip installed jupyter-kernel-gateway.

**Comment by shroominic** [comment]
I just released v0.0.10 which should fix this issue :) 
Just restart the notebook and install it again to get the newest version.
