### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by xiaokui-dev** [shroominic/codeinterpreter-api#67]
ImportError: cannot import name 'get_images' from 'frontend.utils' (/usr/local/Caskroom/miniforge/base/envs/code-interpreter/lib/python3.9/site-packages/frontend/utils.py)

**Comment by devxm** [comment]
Try using from utils import get_images instead

**Comment by devxm** [comment]
Try defining the get_images function in the app.py file

**Comment by shroominic** [comment]
The frontend is really experimental I recommend to checkout the other branch from @GitMarco27 there are some improving updates :)
