### ISSUE TITLE
Use different tools other than python 

### ISSUE THREAD

**Issue by sankethgadadinni** [shroominic/codeinterpreter-api#74]
Is it possible to integrate other tools which helps to just provide reasoning for the given query and not execute any code. Only execute if its needed not all the time?

**Comment by shroominic** [comment]
yeah you can input additional tools in the args
https://github.com/shroominic/codeinterpreter-api/blob/5b58af7d9f1b2bf0cb56396ab77b1a5167b79c53/codeinterpreterapi/session.py#L53C9-L53C47

**Comment by sankethgadadinni** [comment]
Thanks @shroominic
