### ISSUE TITLE
File class to initialize/take content from variable/binary/string - for Chainlit

### ISSUE THREAD

**Issue by ventz** [shroominic/codeinterpreter-api#78]
Hi,

Great work on this project!!

Would it be possible to extend your `File` class (`codeinterpreterapi/schema/file.py`) to provide a `from_content` function, in additional to `from_path` and `from_url`?

That is, to be able to create a `File()` instance from a `content` directly?

This would be key for being able to wrap this within Chainlit

Ex: 
![image](https://github.com/shroominic/codeinterpreter-api/assets/901168/ade0cc01-6463-4ce0-9b5e-d407da4c21cd)
![image](https://github.com/shroominic/codeinterpreter-api/assets/901168/df387900-058b-4c23-9b49-73cd657e42b5)

**Comment by shroominic** [comment]
I mean you can directly use File(name="file_name", content=b"file_content")

**Comment by ventz** [comment]
@shroominic Thanks!

That's what I did for the time being, but assuming since it's not a "public" method, it may change/break over time.

If it's not too much of a hassle, it would be helpful to add.

**Comment by shroominic** [comment]
Good point yeah I try adding this!
