### ISSUE TITLE
Reroute the base OpenAI url to a different domain

### ISSUE THREAD

**Issue by DablewCodes** [shroominic/codeinterpreter-api#81]
My subscription to OpenAI API is through this service: [OpenRouter](https://openrouter.ai/) and I normally call the API through their domain in the following way: 

```
import openai

openai.api_base = "https://openrouter.ai/api/v1"
openai.api_key = $OPENROUTER_API_KEY

response = openai.ChatCompletion.create(
model="openai/gpt-3.5-turbo", # Optional (user controls the default)
messages=[...],
headers={ "HTTP-Referer": $YOUR_SITE_URL, # To identify your app
          "X-Title": $YOUR_APP_NAME },
)
reply = response.choices[0].message
```

Is there a way to change the base api url and add headers to the completion call of this package?

**Comment by shroominic** [comment]
Yeah you can do this with ENV Variables: set the OPENAI_BASE_URL to your one
