### ISSUE TITLE
How to Maintain a Conversation Without Re-Uploading Files?

### ISSUE THREAD

**Issue by alantseone** [shroominic/codeinterpreter-api#83]
Lately, while using the tool, I've noticed that when I have multiple rows/columns in one or more CSV files, the AI asks me some questions to ensure it works effectively, without directly performing analysis. However, here's the challenge: I can't continue the conversation with the AI after answering its questions. Each time, it starts a new conversation upon re-uploading a file. How can I maintain the continuity of the previous conversation? Thank you

**Comment by vinodvarma24** [comment]
Would love to have this feature as well.

**Comment by rosewangrmi** [comment]
Same here. This example did not keep the conversation going. https://github.com/shroominic/codeinterpreter-api/blob/main/examples/chat_history_backend.py

AI says that the message is incomplete when the prompt is "Now for the last 5 years", even though session_id was given to the CodeInterpreterSession

**Comment by shroominic** [comment]
As long as you have the same session open without closing you maintain storage. 
Start the session - do conversations - close the session
